### ISSUE TITLE
推荐MindMaster和Freeplane辅助开发

### ISSUE THREAD

**Issue by Seekladoom** [emako/tcax-creator#2]
老哥开发TCAX Creator的过程中如果要解决C++的数据结构以及TCAS的那些问题的话，可以考虑用MindMaster或者Freeplane这俩思维导图软件分析问题。

【思维导图软件推荐】
Freeplane官网：https://www.freeplane.org/wiki/index.php/Home
MindMaster官网：https://www.edrawsoft.cn/
XMind官网：https://www.xmind.cn/

Freeplane视频教程：
【免费开源可商用】思维导图软件 Freeplane 安装和简单模板制作教程
https://www.bilibili.com/video/BV1AZ4y1L7ky
【免费开源可商用】思维导图软件 Freeplane 常见问题解决方法（不定期更新）
https://www.bilibili.com/video/BV1Pa4y1s7P4

可以用思维导图软件专门针对TCAX的各种开发问题制作思维导图，然后存下来，方便以后开发的时候能够第一时间找到问题入手点以及由思维导图确定的行动逻辑，更快地把开发工作做起来。。。_(:з」∠)_

**Comment by emako** [comment]
?
